# Generated by Django 3.1.1 on 2020-09-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_order_cart'),
        ('Product', '0004_productcart_productcategory_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='users',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
