# Generated by Django 3.1.1 on 2020-09-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_order_cart'),
        ('Product', '0005_cart_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.order'),
        ),
    ]
