# Generated by Django 3.1.1 on 2020-10-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductInfo', '0005_auto_20201004_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
