# Generated by Django 3.1.1 on 2020-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductInfo', '0006_remove_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(to='ProductInfo.Review'),
        ),
    ]
