# Generated by Django 3.0.9 on 2020-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20200926_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='Picture_Picture',
            field=models.ImageField(null=True, upload_to='Images/profile'),
        ),
    ]
