# Generated by Django 3.1.1 on 2020-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_auto_20200926_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_num',
        ),
        migrations.AddField(
            model_name='profile',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Picture_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='Images/profile'),
        ),
    ]
