# Generated by Django 3.0.9 on 2020-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.BigIntegerField(blank=True)),
                ('o_status', models.CharField(blank=True, max_length=200)),
                ('o_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.BigIntegerField(blank=True)),
                ('payment_type', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.BigIntegerField(blank=True)),
                ('u_name', models.CharField(blank=True, max_length=100)),
                ('u_email', models.EmailField(blank=True, max_length=50)),
                ('u_password', models.CharField(blank=True, max_length=50)),
                ('u_address', models.CharField(blank=True, max_length=200)),
                ('u_phone_no', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
