# Generated by Django 3.1.1 on 2020-09-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
